#info:
#    project_name: 'Face recognition'
#    run_name: 'ran_name'
#    date: '19.07.2022'
#    notes: 'Some notes about experiment'
#    tags: 'tag1, tag2, tag3'
#    log_freq: 500
#

common:
    seed: 8


dataset:
    root: '~/PycharmProjects/cvr-hw1-modeling/raw_data/train-jpg/'
    img_type: 'jpg'
    num_channels: 3
    num_classes: 2000
    img_size: 224
    batch_size: 64
    num_workers: 2
    train_augmentations: 'default'
    valid_augmentations: 'default'


model:
    name: 'resnet34'
    model_param1: 1
    model_param2: 2


train:
    trainer:
        devices: 1
        accelerator: 'auto'
        accumulate_grad_batches: 1  # >1 in case of a small batch size
        auto_scale_batch_size: False  # adjustable batch size
        gradient_clip_val: 0.0 # no clip
        benchmark: True
        precision: 32
        profiler: 'simple'
        max_epochs: 10

    ckpt_path: null # train from scratch

    callbacks:
        checkpoint:
            dirpath: './experiments/'
            save_top_k: 3
            monitor: 'val_loss'
            mode: 'min'

    optimizer:
        name: 'AdamW'
        lr: 0.001

    lr_scheduler:
        name: 'ReduceLROnPlateau'
        patience: 5
        factor: 0.5
        mode: 'min'
        min_lr: 0.00001

    criterion:
        name: 'focal_loss'
        gamma: 2


inference:
    batch_size: 128
    num_workers: 2
